services:
  pgdatabase:
    image: postgres:18
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8085:80"
    depends_on:
      - pgdatabase
    networks:
      - pgnetwork

  taxi_ingest:
    image: taxi_ingest:v001
    container_name: taxi_ingest
    depends_on:
      - pgdatabase
    command: >
      --pg-user=root
      --pg-pass=root
      --pg-host=pgdatabase
      --pg-port=5432
      --pg-db=ny_taxi
    networks:
      - pgnetwork
    restart: "no"

networks:
  pgnetwork:
    name: zoomcamp_de_2026_homework_pgnetwork

volumes:
  ny_taxi_postgres_data:
